#ifndef MDT_INFO_H_INCLUDED
#define MDT_INFO_H_INCLUDED

const char *infoCommands[0xFF] =
{
    /* 00 */ "                                 ",
    /* 01 */ "FM TL OP1: 1_80, 0Reset          ",
    /* 02 */ "FM TL OP2: 1_80, 0Reset          ",
    /* 03 */ "FM TL OP3: 1_80, 0Reset          ",
    /* 04 */ "FM TL OP4: 1_80, 0Reset          ",
    /* 05 */ "FM RS: X=1_5 OP,Y=1_4,0Reset     ",
    /* 06 */ "FM MULT: X=1_4 OP,Y=1_F,0Reset   ",
    /* 07 */ "FM DETUNE: X=1_4 OP,Y=1_8,0Reset ",
    /* 08 */ "FM AM: X=1_5 OP,Y=0Reset,1On,2Off",
    /* 09 */ "FM SSG-EG: X=1_5 OP,Y=1_9,0Reset ",
    /* 0A */ "FM ALGORITHM: 1_8,0Reset         ",
    /* 0B */ "FM OP1 FEEDBACK: 1_8,0Reset      ",
    /* 0C */ "FM AMS: 1_7,F=Off,0Reset         ",
    /* 0D */ "FM FMS: 1_3,F=Off,0Reset         ",
    /* 0E */ "FM PAN: 11=C,10=L,01=R,FF=Mute   ",
    /* 0F */ "                                 ",
    /* 10 */ "GLOBAL LFO: 1_8 Frequency        ",
    /* 11 */ "DAC: 1 Enable,0 Disable          ",
    /* 12 */ "CH.3: 1 Special,2 Special+CSM    ",
    /* 13 */ "TEMPO: hInt wait count,0Default  ",
    /* 14 */ "ROW TICK: X=Odd,Y=Even           ",
    /* 15 */ "PSG4: X=1_2 PN/WN,Y=0_4 Tonal    ",
    /* 16 */ "PCM BANK: 1_4                    ",
    /* 17 */ "                                 ",
    /* 18 */ "                                 ",
    /* 19 */ "                                 ",
    /* 1A */ "                                 ",
    /* 1B */ "                                 ",
    /* 1C */ "                                 ",
    /* 1D */ "                                 ",
    /* 1E */ "                                 ",
    /* 1F */ "                                 ",
    /* 20 */ "                                 ",
    /* 21 */ "                                 ",
    /* 22 */ "                                 ",
    /* 23 */ "                                 ",
    /* 24 */ "                                 ",
    /* 25 */ "                                 ",
    /* 26 */ "                                 ",
    /* 27 */ "                                 ",
    /* 28 */ "                                 ",
    /* 29 */ "                                 ",
    /* 2A */ "                                 ",
    /* 2B */ "                                 ",
    /* 2C */ "                                 ",
    /* 2D */ "                                 ",
    /* 2E */ "                                 ",
    /* 2F */ "                                 ",
    /* 30 */ "ARPEGGIATOR SEQUENCE: 0Disable   ",
    /* 31 */ "PITCH U: 1_7F,0Off,FF Rst,FE Hold",
    /* 32 */ "PITCH D: 1_7F,0Off,FF Rst,FE Hold",
    /* 33 */ "VIBRATO: X=Speed,Y=Depth,0Off    ",
    /* 34 */ "VIBRATO SPEED: 1_1A,0Reset 8     ",
    /* 35 */ "VIBRATO DEPTH: 0Reset 2          ",
    /* 36 */ "VIBRATO MODE: 1=U,2=D,0=UD       ",
    /* 37 */ "PORTAMENTO SKIP TICKS: 0..FF     ",
    /* 38 */ "                                 ",
    /* 39 */ "                                 ",
    /* 3A */ "                                 ",
    /* 3B */ "                                 ",
    /* 3C */ "                                 ",
    /* 3D */ "                                 ",
    /* 3E */ "                                 ",
    /* 3F */ "                                 ",
    /* 40 */ "VOLUME SEQUENCE: -- Disable      ",
    /* 41 */ "CHANNEL VOLUME: 01..7F,PSG/8     ",
    /* 42 */ "TREMOLO: X=Speed,Y=Depth,-- Off  ",
    /* 43 */ "TREMOLO SPEED: -- Reset 20       ",
    /* 44 */ "VOL DN: X=Speed,Y=Amount,-- Stop ",
    /* 45 */ "VOL UP: X=Speed,Y=Amount,-- Stop ",
    /* 46 */ "VOL D-MOD: [unimp]               ",
    /* 47 */ "                                 ",
    /* 48 */ "                                 ",
    /* 49 */ "                                 ",
    /* 4A */ "                                 ",
    /* 4B */ "                                 ",
    /* 4C */ "                                 ",
    /* 4D */ "                                 ",
    /* 4E */ "                                 ",
    /* 4F */ "                                 ",
    /* 50 */ "NOTE CUT: After XX ticks         ",
    /* 51 */ "NOTE RETRIGER: After XX ticks    ",
    /* 52 */ "MATRIX JUMP 1_FA Row jump to     ",
    /* 53 */ "PATTERN JUMP: 0_1F Row jump to   ",
    /* 54 */ "NOTE DELAY: By XX ticks          ",
    /* 55 */ "CSM BASE NOTE: 9_5F 'lowpass'    ",
    /* 56 */ "                                 ",
    /* 57 */ "                                 ",
    /* 58 */ "                                 ",
    /* 59 */ "                                 ",
    /* 5A */ "                                 ",
    /* 5B */ "                                 ",
    /* 5C */ "                                 ",
    /* 5D */ "                                 ",
    /* 5E */ "                                 ",
    /* 5F */ "                                 ",
    /* 60 */ "                                 ",
    /* 61 */ "                                 ",
    /* 62 */ "                                 ",
    /* 63 */ "                                 ",
    /* 64 */ "                                 ",
    /* 65 */ "                                 ",
    /* 66 */ "                                 ",
    /* 67 */ "                                 ",
    /* 69 */ "                                 ",
    /* 6A */ "                                 ",
    /* 6B */ "                                 ",
    /* 6C */ "                                 ",
    /* 6D */ "                                 ",
    /* 6E */ "                                 ",
    /* 6F */ "                                 ",
    /* 70 */ "                                 ",
    /* 71 */ "                                 ",
    /* 72 */ "                                 ",
    /* 73 */ "                                 ",
    /* 74 */ "                                 ",
    /* 75 */ "                                 ",
    /* 76 */ "                                 ",
    /* 77 */ "                                 ",
    /* 78 */ "                                 ",
    /* 79 */ "                                 ",
    /* 7A */ "                                 ",
    /* 7B */ "                                 ",
    /* 7C */ "                                 ",
    /* 7D */ "                                 ",
    /* 7E */ "                                 ",
    /* 7F */ "                                 ",
    /* 80 */ "                                 ",
    /* 81 */ "                                 ",
    /* 82 */ "                                 ",
    /* 83 */ "                                 ",
    /* 84 */ "                                 ",
    /* 85 */ "                                 ",
    /* 86 */ "                                 ",
    /* 87 */ "                                 ",
    /* 88 */ "                                 ",
    /* 89 */ "                                 ",
    /* 8A */ "                                 ",
    /* 8B */ "                                 ",
    /* 8C */ "                                 ",
    /* 8D */ "                                 ",
    /* 8E */ "                                 ",
    /* 8F */ "                                 ",
    /* 90 */ "                                 ",
    /* 91 */ "                                 ",
    /* 92 */ "                                 ",
    /* 93 */ "                                 ",
    /* 94 */ "                                 ",
    /* 95 */ "                                 ",
    /* 96 */ "                                 ",
    /* 97 */ "                                 ",
    /* 98 */ "                                 ",
    /* 99 */ "                                 ",
    /* 9A */ "                                 ",
    /* 9B */ "                                 ",
    /* 9C */ "                                 ",
    /* 9D */ "                                 ",
    /* 9E */ "                                 ",
    /* 9F */ "                                 ",
    /* A0 */ "                                 ",
    /* A1 */ "FM AR OP1: 01..20,-- Reset       ",
    /* A2 */ "FM AR OP2: 01..20,-- Reset       ",
    /* A3 */ "FM AR OP3: 01..20,-- Reset       ",
    /* A4 */ "FM AR OP4: 01..20,-- Reset       ",
    /* A5 */ "                                 ",
    /* A6 */ "                                 ",
    /* A7 */ "                                 ",
    /* A8 */ "                                 ",
    /* A9 */ "                                 ",
    /* AA */ "                                 ",
    /* AB */ "                                 ",
    /* AC */ "                                 ",
    /* AD */ "                                 ",
    /* AE */ "                                 ",
    /* AF */ "                                 ",
    /* B0 */ "                                 ",
    /* B1 */ "FM DR1 OP1: 01..20,-- Reset      ",
    /* B2 */ "FM DR1 OP2: 01..20,-- Reset      ",
    /* B3 */ "FM DR1 OP3: 01..20,-- Reset      ",
    /* B4 */ "FM DR1 OP4: 01..20,-- Reset      ",
    /* B5 */ "                                 ",
    /* B6 */ "                                 ",
    /* B7 */ "                                 ",
    /* B8 */ "                                 ",
    /* B9 */ "                                 ",
    /* BA */ "                                 ",
    /* BB */ "                                 ",
    /* BC */ "                                 ",
    /* BD */ "                                 ",
    /* BE */ "                                 ",
    /* BF */ "                                 ",
    /* C0 */ "                                 ",
    /* C1 */ "FM SUSTAIN OP1: 01..10,-- Reset  ",
    /* C2 */ "FM SUSTAIN OP2: 01..10,-- Reset  ",
    /* C3 */ "FM SUSTAIN OP3: 01..10,-- Reset  ",
    /* C4 */ "FM SUSTAIN OP4: 01..10,-- Reset  ",
    /* C5 */ "                                 ",
    /* C6 */ "                                 ",
    /* C7 */ "                                 ",
    /* C8 */ "                                 ",
    /* C9 */ "                                 ",
    /* CA */ "                                 ",
    /* CB */ "                                 ",
    /* CC */ "                                 ",
    /* CD */ "                                 ",
    /* CE */ "                                 ",
    /* CF */ "                                 ",
    /* D0 */ "                                 ",
    /* D1 */ "FM DR2 OP1: 01..20,-- Reset      ",
    /* D2 */ "FM DR2 OP2: 01..20,-- Reset      ",
    /* D3 */ "FM DR2 OP3: 01..20,-- Reset      ",
    /* D4 */ "FM DR2 OP4: 01..20,-- Reset      ",
    /* D5 */ "                                 ",
    /* D6 */ "                                 ",
    /* D7 */ "                                 ",
    /* D8 */ "                                 ",
    /* D9 */ "                                 ",
    /* DA */ "                                 ",
    /* DB */ "                                 ",
    /* DC */ "                                 ",
    /* DD */ "                                 ",
    /* DE */ "                                 ",
    /* DF */ "                                 ",
    /* E0 */ "                                 ",
    /* E1 */ "FM RELEASE OP1: 01..10,-- Reset  ",
    /* E2 */ "FM RELEASE OP2: 01..10,-- Reset  ",
    /* E3 */ "FM RELEASE OP3: 01..10,-- Reset  ",
    /* E4 */ "FM RELEASE OP4: 01..10,-- Reset  ",
    /* E5 */ "                                 ",
    /* E6 */ "                                 ",
    /* E7 */ "                                 ",
    /* E8 */ "                                 ",
    /* E9 */ "                                 ",
    /* EA */ "                                 ",
    /* EB */ "                                 ",
    /* EC */ "                                 ",
    /* ED */ "                                 ",
    /* EE */ "                                 ",
    /* EF */ "                                 ",
    /* F0 */ "                                 ",
    /* F1 */ "                                 ",
    /* F2 */ "                                 ",
    /* F3 */ "                                 ",
    /* F4 */ "                                 ",
    /* F5 */ "                                 ",
    /* F6 */ "                                 ",
    /* F7 */ "                                 ",
    /* F8 */ "                                 ",
    /* F9 */ "                                 ",
    /* FA */ "                                 ",
    /* FB */ "                                 ",
    /* FC */ "                                 ",
    /* FD */ "                                 ",
    /* FE */ "                                 ",
    /* FF */ "                                 "
}; // 33 char max

#endif // MDT_INFO_H_INCLUDED
