#ifndef MDT_INFO_H_INCLUDED
#define MDT_INFO_H_INCLUDED

const char *infoCommands[256];/* =
{
    "",
    "FM TOTAL LEVEL [OP1]            ",
    "FM TOTAL LEVEL [OP2]            ",
    "FM TOTAL LEVEL [OP3]            ",
    "FM TOTAL LEVEL [OP4]            ",
    "FM ADSR RATE SCALE              ",
    "FM FREQUENCY MULTIPLIER         ",
    "FM DETUNE                       ",
    "FM AMPLITUDE MODULATION         ",
    "FM SSG-EG                       ",
    "FM ALGORITHM                    ",
    "FM [OP1] FEEDBACK               ",
    "FM AMPLITUDE MODULATION SCALE   ",
    "FM FREQUENCY MODULATION SCALE   ",
    "FM/DAC PAN                      ",
    "",
    "GLOBAL LFO                      ",
    "FM CH.6                         ",
    "FM CH.3                         ",
    "TEMPO                           ",
    "PATTERN ROW RESOLUTION (PULSES) ",
    "PSG CH.4 NOISE MODE             ",
    "PCM BANK                        ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "MSU MD: CD AUDIO - PLAY ONCE    ",
    "MSU MD: CD AUDIO - PLAY LOOP    ",
    "MSU MD: CD AUDIO - SEEK TIME    ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ARP SEQUENCE MACRO MODE         ",
    "ARP SEQUENCE MACRO              ",
    "PITCH SLIDE UP                  ",
    "PITCH SLIDE DOWN                ",
    "VIBRATO                         ",
    "VIBRATO SPEED                   ",
    "VIBRATO DEPTH                   ",
    "VIBRATO MODE                    ",
    "PITCH SLIDE SKIP PULSES         ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "VOL EQUENCE MACRO MODE          ",
    "VOL EQUENCE MACRO               ",
    "CHANNEL VOLUME ATTENUATION      ",
    "TREMOLO                         ",
    "TREMOLO SPEED                   ",
    "VOLUME SLIDE DOWN               ",
    "VOLUME SLIDE UP                 ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NOTE CUT                        ",
    "NOTE RETRIGER                   ",
    "JUMP TO MATRIX ROW              ",
    "JUMP TO NEXT PATTERN            ",
    "NOTE DELAY                      ",
    "CSM BASE NOTE                   ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "PATTERN SIZE (GLOBAL)           ",
    "CH. PATTERN ROW SHIFT (LEFT)    ",
    "CH. PATTERN ROW SHIFT (RIGHT)   ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "FM ADSR ATTACK RATE [OP1]       ",
    "FM ADSR ATTACK RATE [OP2]       ",
    "FM ADSR ATTACK RATE [OP3]       ",
    "FM ADSR ATTACK RATE [OP4]       ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "FM ADSR DECAY RATE 1 [OP1]      ",
    "FM ADSR DECAY RATE 1 [OP2]      ",
    "FM ADSR DECAY RATE 1 [OP3]      ",
    "FM ADSR DECAY RATE 1 [OP4]      ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "FM ADSR SUSTAIN [OP1]           ",
    "FM ADSR SUSTAIN [OP2]           ",
    "FM ADSR SUSTAIN [OP3]           ",
    "FM ADSR SUSTAIN [OP4]           ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "FM ADSR DECAY RATE 2 [OP1]      ",
    "FM ADSR DECAY RATE 2 [OP2]      ",
    "FM ADSR DECAY RATE 2 [OP3]      ",
    "FM ADSR DECAY RATE 2 [OP4]      ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "FM ADSR RELEASE [OP1]           ",
    "FM ADSR RELEASE [OP2]           ",
    "FM ADSR RELEASE [OP3]           ",
    "FM ADSR RELEASE [OP4]           ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
};*/
const char *infoDescriptions[256];

// for blastem
void InitInfo();

#endif // MDT_INFO_H_INCLUDED
